# Generated by Django 4.0.6 on 2022-08-03 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='shedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('starttime', models.IntegerField()),
                ('endtime', models.IntegerField()),
                ('is_candidates', models.BooleanField(default=True)),
            ],
        ),
    ]
